### ISSUE TITLE
IE11 on Windows 7 - 'play' event only fires once

### ISSUE THREAD

**Issue by xxneon** [zohararad/audio5js#60] opened 2015-02-12 16:18 UTC
It appears that IE11 on Windows 7 only fires the 'play' event when you first play the audio.  If you have the audio play more than once, it no longer broadcasts a play event which breaks the tracking of play / pause in audiojs.

My workaround solution was to replace the 'play' listener with 'playing'.  IE11 appears to fire this event every time audio.play() is called.  Chrome and Firefox also work with using the 'playing' event.

**Comment by zohararad** [comment] 2015-02-13 07:52
@xxneon I'm afraid I cannot reproduce this on my local machine using IE11 on Windows 7. It seems like play/pause events are fired properly.

Did you check that you're using the `on` keyword rather than the `one` keyword to bind event listeners?

**Comment by xxneon** [comment] 2015-02-13 13:37
I am using `on`. (via Angular)  Also, I see the bug when viewing your demo page as well.  http://zohararad.github.io/audio5js/

You have the audio set to loop and after it plays through once it won't pause.  On my machine I traced the error back to when the listeners are added to the audio element itself.

**Comment by zohararad** [comment] 2015-02-15 09:26
The play event is fired correctly when pausing and playing the audio, as per the HTML5 audio spec. Looping doesn't mean the audio needs to pause.

I'm can add the `playing` event support to the HTML5 player if you need to hook into that event specifically, although I'm a bit reluctant to do so as mirroring this behaviour in the Flash version might be a bit of a stretch.

If you need to hook into a loop behaviour, perhaps you can use the `ended` event?

**Comment by xxneon** [comment] 2015-02-16 17:54
So you can't reproduce this odd behavior when you try to play an audio file more than once on IE11? (or if it loops automatically)

**Comment by zohararad** [comment] 2015-02-17 16:39
It's not that I can't reproduce it, it's that checking a simple use case of play/pause fires the events correctly when playing / pausing multiple times.

Are you playing audio in a loop? What exactly are you trying to accomplish / build?

**Comment by xxneon** [comment] 2015-03-02 05:13
Simple play/pause works fine form e as well.  It's only when the audio finishes and you try to play the audio a 2nd time.  The play/pause is broken if you replay the audio.  It also breaks when the audio is set to loop.  Your example page loops the audio and when it starts to loop the audio play/pause is broken.

All I'm trying to do is all the user to replay the audio.  And forcing my code to destroy and recreate the audio just so i can play/pause when replaying the audio seems silly.

IE11 appears to only effectively dispatch the `play` event the 1st time through.  After it reaches the end and you replay the audio it doesn't dispatch `play` events anymore.  It only dispatches `playing` events.

**Comment by zohararad** [comment] 2015-03-02 15:58
Ok... got it - So, would it be possible for you to post a simple example of your code that I can play with? I'll try to re-create the problem in IE11 and find a work-around / fix

**Comment by kamijoutouma** [comment] 2015-11-19 23:47
@xxneon So 8 months with no reply on whether you fixed the issue (with a code example of how to fix) or whether the issue was a false alarm.

@zohararad can you close this if xxneon does not respond within 24-48 hours?

**Comment by zohararad** [comment] 2015-11-20 05:06
@kamijoutouma sure things, thanks for the reminder. @xxneon please let me know where this stands.

**Comment by xxneon** [comment] 2015-11-20 05:45
To fix my issue I changed the following lines..
https://github.com/zohararad/audio5js/blob/master/audio5.js#L552
https://github.com/zohararad/audio5js/blob/master/audio5.js#L567

New Line 552: this.audio.addEventListener('playing', this.listeners.play, false);
New Line 567: this.audio.removeEventListener('playing', this.listeners.play);

All browsers that I tested dispatch play & playing events.  Like I mentioned previously, IE11 correctly dispatches 'play' events during the 1st play of the audio. But when you replay the audio IE11 stops dispatching 'play'.  IE **does** dispatch 'playing' all the time.

I propose changing the event listener that is used to playing since all browsers dispatch play and then playing afterwards.

Hope this helps.

**Comment by kamijoutouma** [comment] 2015-11-20 07:58
@xxneon So are you saying that when you click play after its done playing the browser sends 'playing' instead?
Also if IE is not dispatching 'play' then its a bug in their browser and not in our code because that does not meet the spec for the html5 web audio api e.e
I recommend if there is a way to report such a bug that someone do so immediately and if the bug report exists then try to get more people to know about it since this is something that needs to be fixed.

Also can you reproduce this in edge? If so then add that to the report as well. 

@zohararad
What I'm wondering is why you don't have an event listener to playing already anyway e.e?
Did you not care about the event or just forgot or didn't know about it?

**Comment by kamijoutouma** [comment] 2015-11-20 21:12
just gonna say this safari is the worst browser next to internet explorer because whenever they add something to their browser its always broken when it first is put in because the devs are terrible and don't know what they are doing e.e. 

Microsoft and apple should just go bankrupt if they aren't gonna be serious about their damn browsers :|

**Comment by zohararad** [comment] 2015-11-21 06:26
@kamijoutouma the "playing" event must've slipped my mind. I wasn't trying to replicated the entire event spec, only the useful bits. I'm happy to add it though i need to see how to add it in the Flash version (maybe "play" followed by "playing" immediately)

**Comment by kamijoutouma** [comment] 2015-11-21 06:42
Yeah. They playing event is always fired immediately after play.
Also this issue should be closed based on the fact that the web audio api is not supported by IE at all. But only after an alternative has been choosen (either using real audio tag in IE 9-11 only or falling back on flash in all IE regardless of whether the user specifies an swf path or not).
@zohararad

**Comment by zohararad** [comment] 2015-11-21 06:47
added support for "playing" event firing natively in HTML5 or after "play" event in Flash player. This should allow for selective implementation on annoying browsers. Hope this helps @xxneon

**Closed** 2015-11-21 06:46 UTC
